language: python
python:
    - "2.7"

install:
    - pushd src
    - pip install --extra-index-url https://testpypi.python.org/pypi -r requirements.txt
    - popd
    - pip install -r test_requirements.txt
    - pip install coveralls

script:
    - python runtests.py --with-coverage  --cover-package=src

after_success:
    - coveralls
